"""Render four-model paper tables from frozen aggregate exports; no inference."""

from __future__ import annotations

import csv
import hashlib
import json
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "results/aligned_ablation_20260926"
METHODS = ["SFIBAI", "RE_WO_VIEW", "RE_WO_WEAKLOC", "SYNAP"]
NAMES = dict(zip(METHODS, ["SFibAI", "w/o View", "w/o Weak Loc.", "VCRE-Fib"]))
BEST: list[dict[str, object]] = []


def read_csv(name: str) -> list[dict[str, str]]:
    """Read an immutable source table as exact decimal strings."""
    with (SOURCE / name).open(encoding="utf-8", newline="") as stream:
        return list(csv.DictReader(stream))


def table(
    name: str,
    label: str,
    en: str,
    zh: str,
    headers: list[str],
    rows: list[list[str]],
    spec: str | None = None,
) -> None:
    """Write one bilingual table without modifying numerical sources."""
    spec = spec or "l" + "r" * (len(headers) - 1)
    content = [
        "% Generated by scripts/update_aligned_tables.py from frozen CSVs.",
        r"\begin{table}[!htbp]",
        r"\centering\normalsize",
        rf"\caption{{\lang{{{en}}}{{{zh}}}}}\label{{{label}}}",
        (
            r"\setlength{\tabcolsep}{2pt}"
            if name == "tab06_patient"
            else r"\setlength{\tabcolsep}{3pt}"
        ),
        r"\fitresulttable{%",
        rf"\begin{{tabular}}{{@{{}}{spec}@{{}}}}",
        r"\toprule",
        " & ".join(headers) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        if row == ["RULE"]:
            content.append(r"\midrule")
        else:
            if len(row) != len(headers):
                raise ValueError(f"Invalid row width in {name}: {row}")
            content.append(" & ".join(row) + r" \\")
    content += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    (ROOT / "tables" / f"{name}.tex").write_text(
        "\n".join(content) + "\n", encoding="utf-8"
    )


def values(
    rows: list[dict[str, str]],
    key: str,
    group: str,
    direction: str | None = "min",
    digits: int = 6,
    percent: bool = False,
) -> dict[str, str]:
    """Highlight exact extrema, including all exact ties, before rounding."""
    numeric = {
        row["method"]: Decimal(row[key])
        for row in rows
        if row.get(key) not in (None, "", "N/A")
    }
    if any(not number.is_finite() for number in numeric.values()):
        raise ValueError(f"Nonfinite {group}/{key}")
    if direction not in ("min", "max", None):
        raise ValueError(direction)
    best = (
        (min(numeric.values()) if direction == "min" else max(numeric.values()))
        if numeric and direction
        else None
    )
    winners = [method for method, number in numeric.items() if number == best]
    if direction:
        BEST.append(
            {
                "group": group,
                "metric": key,
                "direction": direction,
                "winners": winners,
                "unrounded_best": str(best),
            }
        )
    result = {}
    for method in METHODS:
        if method not in numeric:
            result[method] = r"\na"
            continue
        number = numeric[method] * (100 if percent else 1)
        text = f"{number:.{digits}f}"
        result[method] = rf"\textbf{{{text}}}" if method in winners else text
    return result


def metric_rows(
    rows: list[dict[str, str]],
    specs: list[tuple[str, str, str | None, int, bool]],
    group: str,
) -> list[list[str]]:
    """Build a readable metric-by-model layout."""
    result = []
    for key, label, direction, digits, percent in specs:
        numbers = values(rows, key, group, direction, digits, percent)
        result.append([label] + [numbers[m] for m in METHODS])
    return result


def main() -> None:
    """Validate bindings, render tables, and save the highlighting audit."""
    BEST.clear()
    bindings = json.loads((SOURCE / "source_bindings.json").read_text(encoding="utf-8"))
    primary = read_csv("test/primary.csv")
    validation = read_csv("val/primary.csv")
    for split, rows, counts in [
        ("test", primary, (4107, 240, 4)),
        ("val", validation, (20880, 1227, 33)),
    ]:
        if len(rows) != 4 or {r["method"] for r in rows} != set(METHODS):
            raise ValueError(f"Expected exactly four models for {split}")
        for row in rows:
            frozen = bindings["records"][row["method"]]["freeze"]
            if (
                row["checkpoint_sha256"] != frozen["checkpoint_sha256"]
                or int(row["epoch"]) != frozen["epoch"]
            ):
                raise ValueError("Checkpoint binding mismatch")
            if (
                row["frozen"] != "True"
                or row["seed"] != "2026"
                or row["split"] != split
            ):
                raise ValueError("Unexpected evaluation identity")
            if (
                tuple(int(row[k]) for k in ("n_images", "n_patients", "n_centers"))
                != counts
            ):
                raise ValueError("Cohort count mismatch")
            expected = (
                Decimal(".4") * Decimal(row["image_COR"])
                + Decimal(".4") * Decimal(row["patient_max_COR"])
                + Decimal(".2") * Decimal(row["center_COR"])
            )
            if abs(expected - Decimal(row["R_final"])) > Decimal("1e-14"):
                raise ValueError("Primary endpoint arithmetic mismatch")
    ordered = sorted(primary, key=lambda r: Decimal(r["R_final"]))
    for rank, row in enumerate(ordered, 1):
        if int(row["rank"]) != rank:
            raise ValueError("Saved test ranking mismatch")
    highlight_en = (
        " Bold denotes the best unrounded value per metric; exact ties are all bold."
    )
    highlight_zh = "各指标按未取整数值加粗最优项，精确并列者均加粗。"
    keys = [
        "R_final",
        "image_COR",
        "patient_max_COR",
        "patient_median_COR",
        "center_COR",
    ]
    nums = {key: values(primary, key, "test_primary") for key in keys}
    table(
        "tab01_main",
        "tab:main",
        "Test set primary results: 4,107 images, 240 patients, four centers. All checkpoints were frozen after validation selection. All risks are lower-is-better."
        + highlight_en,
        "Test set 主结果：4,107 图、240 患者、4 中心；全部检查点经验证集选择后冻结，风险均越低越好。"
        + highlight_zh,
        [
            "Rank",
            "Method",
            r"$R_{\mathrm{final}}$",
            "Image COR",
            "Max COR",
            "Median COR",
            "Center COR",
        ],
        [
            [r["rank"], NAMES[r["method"]]] + [nums[k][r["method"]] for k in keys]
            for r in ordered
        ],
        "rlrrrrr",
    )
    keys = ["R_final", "delta_vs_SFIBAI", "relative_delta_percent_vs_SFIBAI"]
    nums = {
        key: values(
            primary, key, "test_difference", digits=3 if "percent" in key else 6
        )
        for key in keys
    }
    table(
        "tab04_comparison",
        "tab:comparison",
        "Observed test differences relative to SFibAI. Differences are method minus baseline; relative differences divide by the baseline, using unrounded values."
        + highlight_en,
        "四模型相对 SFibAI 的测试集观测差异。差值为方法减基线，相对差除以基线，均用未取整数值计算。"
        + highlight_zh,
        [
            "Method",
            "Rank",
            r"$R_{\mathrm{final}}\downarrow$",
            r"$\Delta$ absolute $\downarrow$",
            r"$\Delta$ relative (\%) $\downarrow$",
        ],
        [
            [NAMES[r["method"]], r["rank"]] + [nums[k][r["method"]] for k in keys]
            for r in ordered
        ],
    )
    table(
        "tab02_matrix",
        "tab:matrix",
        "Compared models and inference outputs. All use image-only inference, the same backbone initialization and grading objective. Deletion variants retain the regional grading path and are trained independently.",
        "比较模型及推理输出。均只输入图像，骨干初始化与评分目标一致；删除变体保留区域评分路径，并独立训练。",
        ["Method", "View module", "Weak-localization module", "Outputs"],
        [
            ["SFibAI", "Absent", "Absent", "Score"],
            ["w/o View", "Removed", "Retained", "Score + region"],
            ["w/o Weak Loc.", "Retained", "Removed", "Score + view"],
            ["VCRE-Fib", "Retained", "Retained", "Score + view + region"],
        ],
        "llll",
    )
    image_rows = read_csv("test/image_metrics.csv")
    specs: list[tuple[str, str, str | None, int, bool]] = [
        ("mae", r"MAE $\downarrow$", "min", 6, False),
        ("rmse", r"RMSE $\downarrow$", "min", 6, False),
        ("accuracy_within_0_3", r"Acc.$\pm0.3$ (\%) $\uparrow$", "max", 2, True),
        ("accuracy_within_0_5", r"Acc.$\pm0.5$ (\%) $\uparrow$", "max", 2, True),
        ("grade_accuracy", r"4-grade acc. (\%) $\uparrow$", "max", 2, True),
        ("grade_macro_f1", r"Macro-F1 $\uparrow$", "max", 6, False),
        ("tmae", r"TMAE $\downarrow$", "min", 6, False),
        ("severe_error_rate", r"Severe error (\%) $\downarrow$", "min", 2, True),
        ("cor", r"COR $\downarrow$", "min", 6, False),
    ]
    table(
        "tab05_image",
        "tab:image",
        "Image-level test metrics; 4,107 images per model." + highlight_en,
        "图像级测试集指标，每模型 4,107 图。" + highlight_zh,
        ["Metric"] + [NAMES[m] for m in METHODS],
        metric_rows(image_rows, specs, "test_image"),
    )
    patients = read_csv("test/patient_metrics.csv")
    patient_table: list[list[str]] = []
    compact = [specs[i] for i in (0, 2, 3, 4, 6, 7, 8)]
    for level in ("patient_max", "patient_median"):
        rows = [r for r in patients if r["level"] == level]
        nums = {s[0]: values(rows, s[0], level, s[2], s[3], s[4]) for s in compact}
        if patient_table:
            patient_table.append(["RULE"])
        patient_table.extend(
            [
                [NAMES[m], "Max" if level == "patient_max" else "Median"]
                + [nums[s[0]][m] for s in compact]
                for m in METHODS
            ]
        )
    table(
        "tab06_patient",
        "tab:patient",
        "Patient-level test metrics, 240 patients per row. Reference and prediction are aggregated separately; accuracies and severe errors are percentages. Bold compares models within each aggregation.",
        "患者级测试集指标，每行 240 患者；参考与预测分别聚合，准确率和严重错误率以百分数表示。加粗在同一聚合层级内比较。",
        [
            "Method",
            "Level",
            r"MAE $\downarrow$",
            r"\shortstack{Acc.\\$\pm.3\uparrow$}",
            r"\shortstack{Acc.\\$\pm.5\uparrow$}",
            r"4-grade $\uparrow$",
            r"TMAE $\downarrow$",
            r"Severe $\downarrow$",
            r"COR $\downarrow$",
        ],
        patient_table,
        "llrrrrrrr",
    )
    spatial = read_csv("test/spatial_metrics.csv")
    spatial_specs = [
        ("position_n", "View N", None, 0, False),
        ("position_accuracy", r"View acc. (\%) $\uparrow$", "max", 2, True),
        ("position_macro_f1", r"View macro-F1 $\uparrow$", "max", 6, False),
        ("position_ce", r"View CE $\downarrow$", "min", 6, False),
        ("lesion_valid_box_count", "Weak-target N", None, 0, False),
        ("lesion_dice_at_0_5", r"Dice@0.5 $\uparrow$", "max", 6, False),
        ("lesion_iou_at_0_5", r"IoU@0.5 $\uparrow$", "max", 6, False),
    ]
    table(
        "tab07_auxiliary",
        "tab:auxiliary",
        "Spatial test outputs. N/A indicates an absent head. Weak-target N counts eligible images, not rectangles; Dice/IoU measure agreement with local annotations, not complete lesion segmentation."
        + highlight_en,
        "空间输出测试集结果，缺少对应头记 N/A。弱定位 N 是有效图像数而非矩形框数；Dice/IoU 衡量与局部弱标注的一致性，不代表完整病灶分割。"
        + highlight_zh,
        ["Metric"] + [NAMES[m] for m in METHODS],
        metric_rows(spatial, spatial_specs, "test_spatial"),
    )
    probability = read_csv("test/probability_metrics.csv")
    extra = []
    for level in ("patient_max", "patient_median"):
        extra += metric_rows(
            [r for r in patients if r["level"] == level],
            [
                (
                    "rmse",
                    level.replace("_", " ").title() + r" RMSE $\downarrow$",
                    "min",
                    6,
                    False,
                ),
                (
                    "grade_macro_f1",
                    level.replace("_", " ").title() + r" macro-F1 $\uparrow$",
                    "max",
                    6,
                    False,
                ),
            ],
            "extra_" + level,
        )
    extra += [["RULE"]]
    extra += metric_rows(
        probability,
        [
            ("grade_macro_auroc", r"Image macro-AUROC $\uparrow$", "max", 6, False),
            ("grade_macro_auprc", r"Image macro-AUPRC $\uparrow$", "max", 6, False),
            ("grade_brier", r"Image multiclass Brier $\downarrow$", "min", 6, False),
            ("grade_ece", r"Image ECE $\downarrow$", "min", 6, False),
        ],
        "test_probability",
    )
    table(
        "tab14_additional",
        "tab:additional",
        "Additional test grading and image-only probability metrics." + highlight_en,
        "补充测试集分级指标与仅图像级的概率指标。" + highlight_zh,
        ["Metric"] + [NAMES[m] for m in METHODS],
        extra,
    )
    centers = read_csv("test/centers.csv")
    center_rows = []
    for center in sorted({r["center"] for r in centers}):
        rows = [r for r in centers if r["center"] == center]
        center_nums = values(rows, "patient_max_COR", "test_" + center)
        center_rows.append(
            [center.replace("_", r"\_"), rows[0]["images"], rows[0]["patients"]]
            + [center_nums[m] for m in METHODS]
        )
    table(
        "tab15_centers",
        "tab:centers",
        "Per-center test patient-max COR (lower is better). Bold compares methods within a center; small-center estimates remain descriptive.",
        "逐中心测试集 patient-max COR（越低越好），加粗在同一中心内比较；小中心估计仅作描述。",
        ["Center", "Images", "Patients"] + [NAMES[m] for m in METHODS],
        center_rows,
    )
    views = read_csv("test/view_classes.csv")
    view_rows = []
    for label in sorted({r["label"] for r in views}, key=int):
        rows = [r for r in views if r["label"] == label]
        view_nums = values(rows, "recall", "test_view_" + label, "max", 2, True)
        view_rows.append(
            [
                label,
                rows[0]["name"],
                rows[0]["support"],
                view_nums["RE_WO_WEAKLOC"],
                view_nums["SYNAP"],
            ]
        )
    table(
        "tab13_views",
        "tab:views",
        "Six acquisition views and test recall (percent). Bold compares the two view-capable models within each class. Main-paper cases cover four true views.",
        "六类扫查切面与测试集召回率（百分数），在每类的两个含切面头模型中加粗最优项；正文病例覆盖四种真实切面。",
        ["View", "Anatomical/acquisition view", "N", "w/o Weak Loc.", "VCRE-Fib"],
        view_rows,
        r"lp{.49\linewidth}rrr",
    )
    resources = read_csv("resources.csv")
    resource_rows: list[list[str]] = []
    resource_keys = [
        "parameters",
        "gmacs_per_image",
        "latency_median_ms",
        "latency_p95_ms",
        "peak_allocated_mib",
    ]
    for batch in ("1", "8"):
        rows = [r for r in resources if r["batch_size"] == batch]
        nums = {
            k: values(
                rows,
                k,
                "resources_batch_" + batch,
                digits=0 if k == "parameters" else 3,
            )
            for k in resource_keys
        }
        if resource_rows:
            resource_rows.append(["RULE"])
        resource_rows.extend(
            [[NAMES[m], batch] + [nums[k][m] for k in resource_keys] for m in METHODS]
        )
    table(
        "tab09_resources",
        "tab:resources",
        "Matched resource measurements; latency is milliseconds per batch and memory is peak allocated MiB. All quantities are lower-is-better; bold compares models within each batch size.",
        "统一条件下的资源测量：延迟为毫秒/批次，显存为峰值已分配 MiB。数值均越低越好，加粗在同一 batch size 内比较。",
        [
            "Method",
            "Batch",
            "Parameters",
            "GMACs/image",
            "Median ms",
            "P95 ms",
            "Peak MiB",
        ],
        resource_rows,
    )
    nums = {
        k: values(validation, k, "validation_selection")
        for k in ("R_final", "image_COR")
    }
    val_by_method = {r["method"]: r for r in validation}
    table(
        "tab10_freeze",
        "tab:freeze",
        "Validation-selected frozen checkpoints. Validation: 20,880 images, 1,227 patients, 33 centers. All four methods, including VCRE-Fib, use a 90-epoch cap for the training comparison; checkpoints are selected from epochs 21--90."
        + highlight_en,
        "验证集选择并冻结的检查点；验证集含 20,880 图、1,227 患者、33 中心。包括 VCRE-Fib 在内的四个方法均以 90 epoch 为训练比较上限，检查点从第 21--90 epoch 中选择。"
        + highlight_zh,
        [
            "Method",
            "Epoch cap",
            "Selected epoch",
            r"Val $R_{\mathrm{final}}\downarrow$",
            r"Val image COR $\downarrow$",
        ],
        [
            [
                NAMES[m],
                "90",
                val_by_method[m]["epoch"],
                nums["R_final"][m],
                nums["image_COR"][m],
            ]
            for m in METHODS
        ],
    )
    manifest = {
        str(p.relative_to(SOURCE))
        .replace("\\", "/"): hashlib.sha256(p.read_bytes())
        .hexdigest()
        for p in sorted(SOURCE.rglob("*.csv"))
    }
    audit = {
        "status": "PASS",
        "source": str(SOURCE.relative_to(ROOT)),
        "source_sha256": manifest,
        "highlighting": BEST,
        "precision_rule": "Decimal extrema before display rounding; exact ties all bold",
        "inference_calls": 0,
        "bootstrap_calls": 0,
        "training_calls": 0,
    }
    (ROOT / "audits").mkdir(exist_ok=True)
    (ROOT / "audits/ALIGNED_TABLE_CHECKS.json").write_text(
        json.dumps(audit, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"Rendered 11 four-model tables; checked {len(BEST)} metric comparisons.")


if __name__ == "__main__":
    main()
