name: cv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - opencv
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - torch
      - torchvision
      - tensorboard
